language: cpp

sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-5.0
            - cmake
            - cmake-data
            - g++-6
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=clang-5.0
        - CMAKE_CXX_COMPILER=clang++-5.0
        - ENABLE_SHARED_LIBS=ON

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-5.0
            - cmake
            - cmake-data
            - g++-6
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=clang-5.0
        - CMAKE_CXX_COMPILER=clang++-5.0
        - ENABLE_SHARED_LIBS=ON

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-6
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=gcc-6
        - CMAKE_CXX_COMPILER=g++-6
        - ENABLE_SHARED_LIBS=ON

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-6
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=gcc-6
        - CMAKE_CXX_COMPILER=g++-6
        - ENABLE_SHARED_LIBS=ON

    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=clang
        - CMAKE_CXX_COMPILER=clang++
        - ENABLE_SHARED_LIBS=OFF

    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=clang
        - CMAKE_CXX_COMPILER=clang++
        - ENABLE_SHARED_LIBS=OFF

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew outdated boost || brew upgrade boost;
      ./install_dependencies.sh
    else
      sudo add-apt-repository -y ppa:samuel-bachmann/boost;
      sudo apt-get update;
      sudo apt-get install libboost1.58-dev libboost-date-time1.58.0 libboost-filesystem1.58-dev libboost-system1.58-dev libboost-thread1.58-dev libboost-regex1.58-dev libboost-program-options1.58-dev 
      ./install_dependencies.sh
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
          -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
          -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
          -DENABLE_SHARED_LIBS=${ENABLE_SHARED_LIBS}
          ..

script:
  - make -j2

